# ==== Required ====
dbc: "DBCs/Megatron_Proposed_test.dbc"

# ==== CAN ====
# iface: "can0"           # CAN interface
iface: "PCAN_USBBUS1"           # CAN interface

# ==== Sinks (choose one or both) ====
to_file: true           # write decoded CSV
to_console: true       # print decoded lines to stdout

# ==== File options (only used if to_file = true) ====
out_dir: "logs"
base_name: ""           # "" -> auto timestamped canlog_YYYYMMDD_HHMMSS
flush_sec: 2.0

# ==== Formatting / policy ====
decoded_flat: true      # true: one row per message (signals as JSON); false: one row per signal
drop_unknown: true     # true: skip frames not found in DBC
